name = "pile-chat"
compatibility_date = "2023-01-01"
node_compat = true
compatibility_flags = [ "nodejs_compat" ]

[vars]
ENVIRONMENT = 'dev'
CUSTOM_HEADERS_TO_IGNORE = []

#
#Configuration for DEVELOPMENT environment
#
[env.staging]
name = "pile-chat-dev"

[env.staging.vars]
ENVIRONMENT = 'staging'
CUSTOM_HEADERS_TO_IGNORE = []


#
#Configuration for PRODUCTION environment
#
[env.production]
name = "pile-chat"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []

[placement]
mode = "smart"
